[versions]
androidx-core = "1.7.0"
androidx-appcompat = "1.4.1"
androidx-lifecycle = "2.4.0"
androidx-navigation = "2.4.1"
androidx-annotation = "1.3.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-paging = "3.1.0"
google-material = "1.5.0"
google-gson = "2.8.8"
dagger-hilt = "2.38.1"
coroutine = "1.6.0"
retrofit = "2.9.0"
okhttp = "4.9.3"
glide = "4.13.0"
other-timber = "5.0.1"
other-chucker = "3.5.2"
other-shimmer = "0.5.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-okhttp3 = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }

other-timber = { module = "com.jakewharton.timber:timber", version.ref = "other-timber" }
other-chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "other-chucker" }
other-chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "other-chucker" }
other-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "other-shimmer" }